# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared.grpc_gen.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\x1a\x0c\x63ommon.proto\"1\n\tStockItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"%\n\x0fGetStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"u\n\x10GetStockResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x1a\n\x12\x61vailable_quantity\x18\x02 \x01(\x05\x12\x19\n\x11reserved_quantity\x18\x03 \x01(\x05\x12\x16\n\x0etotal_quantity\x18\x04 \x01(\x05\"d\n\x13ReserveStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12#\n\x05items\x18\x02 \x03(\x0b\x32\x14.inventory.StockItem\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\"d\n\x14ReserveStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t\"W\n\x13ReleaseStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\"8\n\x14ReleaseStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"W\n\x13\x43onfirmStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\"8\n\x14\x43onfirmStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xca\x02\n\x10InventoryService\x12\x43\n\x08GetStock\x12\x1a.inventory.GetStockRequest\x1a\x1b.inventory.GetStockResponse\x12O\n\x0cReserveStock\x12\x1e.inventory.ReserveStockRequest\x1a\x1f.inventory.ReserveStockResponse\x12O\n\x0cReleaseStock\x12\x1e.inventory.ReleaseStockRequest\x1a\x1f.inventory.ReleaseStockResponse\x12O\n\x0c\x43onfirmStock\x12\x1e.inventory.ConfirmStockRequest\x1a\x1f.inventory.ConfirmStockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKITEM']._serialized_start=44
  _globals['_STOCKITEM']._serialized_end=93
  _globals['_GETSTOCKREQUEST']._serialized_start=95
  _globals['_GETSTOCKREQUEST']._serialized_end=132
  _globals['_GETSTOCKRESPONSE']._serialized_start=134
  _globals['_GETSTOCKRESPONSE']._serialized_end=251
  _globals['_RESERVESTOCKREQUEST']._serialized_start=253
  _globals['_RESERVESTOCKREQUEST']._serialized_end=353
  _globals['_RESERVESTOCKRESPONSE']._serialized_start=355
  _globals['_RESERVESTOCKRESPONSE']._serialized_end=455
  _globals['_RELEASESTOCKREQUEST']._serialized_start=457
  _globals['_RELEASESTOCKREQUEST']._serialized_end=544
  _globals['_RELEASESTOCKRESPONSE']._serialized_start=546
  _globals['_RELEASESTOCKRESPONSE']._serialized_end=602
  _globals['_CONFIRMSTOCKREQUEST']._serialized_start=604
  _globals['_CONFIRMSTOCKREQUEST']._serialized_end=691
  _globals['_CONFIRMSTOCKRESPONSE']._serialized_start=693
  _globals['_CONFIRMSTOCKRESPONSE']._serialized_end=749
  _globals['_INVENTORYSERVICE']._serialized_start=752
  _globals['_INVENTORYSERVICE']._serialized_end=1082
# @@protoc_insertion_point(module_scope)
