# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared.grpc_gen.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\x1a\x0c\x63ommon.proto\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\")\n\x15GetOrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"t\n\x10OrderItemMessage\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x12\n\nunit_price\x18\x04 \x01(\x01\x12\x10\n\x08subtotal\x18\x05 \x01(\x01\"\xd6\x01\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12&\n\x05items\x18\x06 \x03(\x0b\x32\x17.order.OrderItemMessage\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\t \x01(\t\"K\n\x13OrderStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nupdated_at\x18\x03 \x01(\t2\x94\x01\n\x0cOrderService\x12\x38\n\x08GetOrder\x12\x16.order.GetOrderRequest\x1a\x14.order.OrderResponse\x12J\n\x0eGetOrderStatus\x12\x1c.order.GetOrderStatusRequest\x1a\x1a.order.OrderStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETORDERREQUEST']._serialized_start=36
  _globals['_GETORDERREQUEST']._serialized_end=71
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=73
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=114
  _globals['_ORDERITEMMESSAGE']._serialized_start=116
  _globals['_ORDERITEMMESSAGE']._serialized_end=232
  _globals['_ORDERRESPONSE']._serialized_start=235
  _globals['_ORDERRESPONSE']._serialized_end=449
  _globals['_ORDERSTATUSRESPONSE']._serialized_start=451
  _globals['_ORDERSTATUSRESPONSE']._serialized_end=526
  _globals['_ORDERSERVICE']._serialized_start=529
  _globals['_ORDERSERVICE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
