# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared.grpc_gen.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\x1a\x0c\x63ommon.proto\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"t\n\x0fProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x11\n\tis_active\x18\x06 \x01(\x08\"4\n\x0cValidateItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"?\n\x17ValidateProductsRequest\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.product.ValidateItem\"r\n\x16ValidatedProductDetail\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08is_valid\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\"s\n\x18ValidateProductsResponse\x12\x11\n\tall_valid\x18\x01 \x01(\x08\x12.\n\x05items\x18\x02 \x03(\x0b\x32\x1f.product.ValidatedProductDetail\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x01\x32\xad\x01\n\x0eProductService\x12\x42\n\nGetProduct\x12\x1a.product.GetProductRequest\x1a\x18.product.ProductResponse\x12W\n\x10ValidateProducts\x12 .product.ValidateProductsRequest\x1a!.product.ValidateProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=40
  _globals['_GETPRODUCTREQUEST']._serialized_end=79
  _globals['_PRODUCTRESPONSE']._serialized_start=81
  _globals['_PRODUCTRESPONSE']._serialized_end=197
  _globals['_VALIDATEITEM']._serialized_start=199
  _globals['_VALIDATEITEM']._serialized_end=251
  _globals['_VALIDATEPRODUCTSREQUEST']._serialized_start=253
  _globals['_VALIDATEPRODUCTSREQUEST']._serialized_end=316
  _globals['_VALIDATEDPRODUCTDETAIL']._serialized_start=318
  _globals['_VALIDATEDPRODUCTDETAIL']._serialized_end=432
  _globals['_VALIDATEPRODUCTSRESPONSE']._serialized_start=434
  _globals['_VALIDATEPRODUCTSRESPONSE']._serialized_end=549
  _globals['_PRODUCTSERVICE']._serialized_start=552
  _globals['_PRODUCTSERVICE']._serialized_end=725
# @@protoc_insertion_point(module_scope)
